// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversationRows,
    messageRows,
    conversationMcpServerRows,
    chatStorageMetaRows,
    messagePartRows,
    providerArtifactRows,
    assetRows,
    messageAssetRows,
    assetGcRows,
    gcAuditRows,
    assetReferenceDirtyRows,
    generationRunRows,
    assistantRows,
    providerRows,
    providerGroupRows,
    mcpServerRows,
    worldBookRows,
    assistantMemoryRows,
    quickPhraseRows,
    searchServiceRows,
    ttsServiceRows,
    instructionInjectionRows,
    assistantTagRows,
    preferenceRows,
    memoryEntryRows,
    userProfileFieldRows,
    messagePromptRows,
    idxConversationsUpdatedAt,
    idxConversationsAssistant,
    idxMessagesConversationOrder,
    idxMessagesConversationTimestamp,
    idxMessagesGroup,
    idxMessageRowsStreaming,
    idxMessagePartsRevisionOrdinal,
    idxProviderArtifactsRevisionKind,
    idxMessageAssetsAsset,
    idxGenerationRunsActiveTarget,
    idxGenerationRunsStateUpdated,
    idxAssistantMemoriesAssistant,
    idxMemoryEntriesVisible,
    idxMemoryEntriesRecent,
    idxMemoryEntriesDedupe,
    idxMessagePromptsConversationSnapshot,
  ];
  late final Shape0 conversationRows = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversation_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messageRows = Shape1(
    source: i0.VersionedTable(
      entityName: 'message_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, message_order)',
        'UNIQUE(conversation_id, group_id, version)',
      ],
      columns: [
        _column_0,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 conversationMcpServerRows = Shape2(
    source: i0.VersionedTable(
      entityName: 'conversation_mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(conversation_id, server_id)',
        'UNIQUE(conversation_id, ordinal)',
      ],
      columns: [_column_15, _column_33, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 chatStorageMetaRows = Shape3(
    source: i0.VersionedTable(
      entityName: 'chat_storage_meta_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 messagePartRows = Shape4(
    source: i0.VersionedTable(
      entityName: 'message_part_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(revision_id, ordinal)',
        'FOREIGN KEY(revision_id)REFERENCES message_rows(id)ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED',
        'CHECK(updated_at >= created_at)',
      ],
      columns: [
        _column_37,
        _column_38,
        _column_39,
        _column_34,
        _column_40,
        _column_41,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 providerArtifactRows = Shape5(
    source: i0.VersionedTable(
      entityName: 'provider_artifact_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(revision_id, kind)',
        'FOREIGN KEY(revision_id)REFERENCES message_rows(id)ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED',
        'CHECK(updated_at >= created_at)',
      ],
      columns: [
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 assetRows = Shape6(
    source: i0.VersionedTable(
      entityName: 'asset_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_2,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 messageAssetRows = Shape7(
    source: i0.VersionedTable(
      entityName: 'message_asset_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(revision_id, asset_id, kind)'],
      columns: [_column_38, _column_49, _column_50, _column_40],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 assetGcRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'asset_gc_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(asset_id)'],
      columns: [_column_50, _column_51, _column_52, _column_53],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 gcAuditRows = Shape9(
    source: i0.VersionedTable(
      entityName: 'gc_audit_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_54, _column_55, _column_56, _column_57],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 assetReferenceDirtyRows = Shape10(
    source: i0.VersionedTable(
      entityName: 'asset_reference_dirty_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(revision_id)'],
      columns: [_column_49],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 generationRunRows = Shape11(
    source: i0.VersionedTable(
      entityName: 'generation_run_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'FOREIGN KEY(target_revision_id)REFERENCES message_rows(id)DEFERRABLE INITIALLY DEFERRED',
        'CHECK(updated_at >= created_at)',
        'CHECK(terminal_at IS NULL OR terminal_at >= created_at)',
        'CHECK((state IN (\'preparing\', \'requesting\', \'streaming\', \'waiting_tool\') AND terminal_at IS NULL)OR(state IN (\'completed\', \'failed\', \'cancelled\', \'interrupted\') AND terminal_at IS NOT NULL))',
        'CHECK(error_code IS NULL OR(length(error_code) BETWEEN 1 AND 128 AND state IN (\'failed\', \'cancelled\', \'interrupted\')))',
      ],
      columns: [
        _column_0,
        _column_15,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_2,
        _column_3,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 assistantRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'assistant_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 providerRows = Shape13(
    source: i0.VersionedTable(
      entityName: 'provider_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(provider_key)'],
      columns: [_column_65, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 providerGroupRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'provider_group_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 mcpServerRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 worldBookRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'world_book_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 assistantMemoryRows = Shape14(
    source: i0.VersionedTable(
      entityName: 'assistant_memory_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_66, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 quickPhraseRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'quick_phrase_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 searchServiceRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'search_service_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 ttsServiceRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'tts_service_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 instructionInjectionRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'instruction_injection_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 assistantTagRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'assistant_tag_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 preferenceRows = Shape15(
    source: i0.VersionedTable(
      entityName: 'preference_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_35, _column_36, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 memoryEntryRows = Shape16(
    source: i0.VersionedTable(
      entityName: 'memory_entry_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK((scope = \'global\' AND assistant_id IS NULL)OR(scope = \'assistant\' AND assistant_id IS NOT NULL))',
        'CHECK(entry_updated_at >= entry_created_at)',
      ],
      columns: [
        _column_0,
        _column_64,
        _column_67,
        _column_5,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_41,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 userProfileFieldRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'user_profile_field_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 messagePromptRows = Shape17(
    source: i0.VersionedTable(
      entityName: 'message_prompt_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(revision_id)',
        'FOREIGN KEY(revision_id)REFERENCES message_rows(id)ON DELETE CASCADE',
      ],
      columns: [_column_39, _column_38, _column_41, _column_74, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxConversationsUpdatedAt = i1.Index(
    'idx_conversations_updated_at',
    'CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at DESC, id ASC)',
  );
  final i1.Index idxConversationsAssistant = i1.Index(
    'idx_conversations_assistant',
    'CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id)',
  );
  final i1.Index idxMessagesConversationOrder = i1.Index(
    'idx_messages_conversation_order',
    'CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order, id)',
  );
  final i1.Index idxMessagesConversationTimestamp = i1.Index(
    'idx_messages_conversation_timestamp',
    'CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp, id)',
  );
  final i1.Index idxMessagesGroup = i1.Index(
    'idx_messages_group',
    'CREATE INDEX idx_messages_group ON message_rows (conversation_id, group_id, version, id)',
  );
  final i1.Index idxMessageRowsStreaming = i1.Index(
    'idx_message_rows_streaming',
    'CREATE INDEX idx_message_rows_streaming ON message_rows (id) WHERE is_streaming = 1',
  );
  final i1.Index idxMessagePartsRevisionOrdinal = i1.Index(
    'idx_message_parts_revision_ordinal',
    'CREATE INDEX idx_message_parts_revision_ordinal ON message_part_rows (conversation_id, revision_id, ordinal)',
  );
  final i1.Index idxProviderArtifactsRevisionKind = i1.Index(
    'idx_provider_artifacts_revision_kind',
    'CREATE INDEX idx_provider_artifacts_revision_kind ON provider_artifact_rows (conversation_id, revision_id, kind)',
  );
  final i1.Index idxMessageAssetsAsset = i1.Index(
    'idx_message_assets_asset',
    'CREATE INDEX idx_message_assets_asset ON message_asset_rows (asset_id, revision_id)',
  );
  final i1.Index idxGenerationRunsActiveTarget = i1.Index(
    'idx_generation_runs_active_target',
    'CREATE UNIQUE INDEX idx_generation_runs_active_target ON generation_run_rows (conversation_id, target_revision_id) WHERE state IN (\'preparing\', \'requesting\', \'streaming\', \'waiting_tool\')',
  );
  final i1.Index idxGenerationRunsStateUpdated = i1.Index(
    'idx_generation_runs_state_updated',
    'CREATE INDEX idx_generation_runs_state_updated ON generation_run_rows (state, updated_at, id)',
  );
  final i1.Index idxAssistantMemoriesAssistant = i1.Index(
    'idx_assistant_memories_assistant',
    'CREATE INDEX idx_assistant_memories_assistant ON assistant_memory_rows (assistant_id, id)',
  );
  final i1.Index idxMemoryEntriesVisible = i1.Index(
    'idx_memory_entries_visible',
    'CREATE INDEX idx_memory_entries_visible ON memory_entry_rows (status, type, scope, assistant_id)',
  );
  final i1.Index idxMemoryEntriesRecent = i1.Index(
    'idx_memory_entries_recent',
    'CREATE INDEX idx_memory_entries_recent ON memory_entry_rows (status, type, entry_updated_at, id)',
  );
  final i1.Index idxMemoryEntriesDedupe = i1.Index(
    'idx_memory_entries_dedupe',
    'CREATE INDEX idx_memory_entries_dedupe ON memory_entry_rows (scope, assistant_id, type, content_normalized)',
  );
  final i1.Index idxMessagePromptsConversationSnapshot = i1.Index(
    'idx_message_prompts_conversation_snapshot',
    'CREATE INDEX idx_message_prompts_conversation_snapshot ON message_prompt_rows (conversation_id, carries_memory_snapshot)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isPinned =>
      columnsByName['is_pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get assistantId =>
      columnsByName['assistant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get truncateIndex =>
      columnsByName['truncate_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get versionSelectionsJson =>
      columnsByName['version_selections_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSummarizedMessageCount =>
      columnsByName['last_summarized_message_count']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get chatSuggestionsJson =>
      columnsByName['chat_suggestions_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get injectedMemoryHash =>
      columnsByName['injected_memory_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastMemoryExtractedOrder =>
      columnsByName['last_memory_extracted_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get chatModelProvider =>
      columnsByName['chat_model_provider']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get chatModelId =>
      columnsByName['chat_model_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_pinned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_pinned IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'assistant_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'truncate_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT (-1) CHECK (truncate_index >= -1)',
      defaultValue: const i1.CustomExpression('-1'),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version_selections_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summary',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_summarized_message_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (last_summarized_message_count >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chat_suggestions_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'injected_memory_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_memory_extracted_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT (-1) CHECK (last_memory_extracted_order >= -1)',
      defaultValue: const i1.CustomExpression('-1'),
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chat_model_provider',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chat_model_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timestamp =>
      columnsByName['timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get modelId =>
      columnsByName['model_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalTokens =>
      columnsByName['total_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isStreaming =>
      columnsByName['is_streaming']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reasoningStartAt =>
      columnsByName['reasoning_start_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reasoningFinishedAt =>
      columnsByName['reasoning_finished_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get translation =>
      columnsByName['translation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reasoningSegmentsJson =>
      columnsByName['reasoning_segments_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promptTokens =>
      columnsByName['prompt_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completionTokens =>
      columnsByName['completion_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cachedTokens =>
      columnsByName['cached_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get messageOrder =>
      columnsByName['message_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conversation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES conversation_rows(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (role IS NOT \'\')',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'timestamp',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provider_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (total_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_streaming',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_streaming IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reasoning_start_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reasoning_finished_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'translation',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reasoning_segments_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (version >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'prompt_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (prompt_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completion_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (completion_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cached_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (cached_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (duration_ms >= 0)',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'message_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (message_order >= 0)',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (ordinal >= 0)',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get partId =>
      columnsByName['part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get revisionId =>
      columnsByName['revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'part_id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conversation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'revision_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (kind IS NOT \'\')',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get revisionId =>
      columnsByName['revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentHash =>
      columnsByName['content_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteSize =>
      columnsByName['byte_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get thumbnailPath =>
      columnsByName['thumbnail_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastReferencedAt =>
      columnsByName['last_referenced_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (byte_size >= 0)',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'width',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (width > 0)',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'height',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (height > 0)',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumbnail_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_referenced_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get revisionId =>
      columnsByName['revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assetId =>
      columnsByName['asset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'revision_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES message_rows(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'asset_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES asset_rows(id)ON DELETE CASCADE',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get assetId =>
      columnsByName['asset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get notBefore =>
      columnsByName['not_before']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get generation =>
      columnsByName['generation']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'not_before',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (attempts >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'generation',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (generation >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get revisionId =>
      columnsByName['revision_id']! as i1.GeneratedColumn<String>;
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get targetRevisionId =>
      columnsByName['target_revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get stateRevision =>
      columnsByName['state_revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get checkpointSeq =>
      columnsByName['checkpoint_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get errorCode =>
      columnsByName['error_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get terminalAt =>
      columnsByName['terminal_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_revision_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'state',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (state IN (\'preparing\', \'requesting\', \'streaming\', \'waiting_tool\', \'completed\', \'failed\', \'cancelled\', \'interrupted\'))',
);
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'state_revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (state_revision >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'checkpoint_seq',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (checkpoint_seq >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'terminal_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (sort_order >= 0)',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get providerKey =>
      columnsByName['provider_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provider_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get assistantId =>
      columnsByName['assistant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'assistant_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assistantId =>
      columnsByName['assistant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentNormalized =>
      columnsByName['content_normalized']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get entryCreatedAt =>
      columnsByName['entry_created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get entryUpdatedAt =>
      columnsByName['entry_updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scope',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (scope IN (\'global\', \'assistant\'))',
    );
i1.GeneratedColumn<String> _column_68(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'type',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (type IN (\'identity\', \'workflow\', \'voice\', \'instruction\'))',
);
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (status IN (\'active\', \'archived\'))',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_normalized',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'entry_created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'entry_updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get revisionId =>
      columnsByName['revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get carriesMemorySnapshot =>
      columnsByName['carries_memory_snapshot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'carries_memory_snapshot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (carries_memory_snapshot IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversationRows,
    messageRows,
    conversationMcpServerRows,
    chatStorageMetaRows,
    messagePartRows,
    providerArtifactRows,
    assetRows,
    messageAssetRows,
    assetGcRows,
    gcAuditRows,
    assetReferenceDirtyRows,
    generationRunRows,
    assistantRows,
    providerRows,
    providerGroupRows,
    mcpServerRows,
    worldBookRows,
    assistantMemoryRows,
    quickPhraseRows,
    searchServiceRows,
    ttsServiceRows,
    instructionInjectionRows,
    assistantTagRows,
    preferenceRows,
    memoryEntryRows,
    userProfileFieldRows,
    messagePromptRows,
    tombstoneRows,
    extensionEntityRows,
    idxConversationsUpdatedAt,
    idxConversationsAssistant,
    idxMessagesConversationOrder,
    idxMessagesConversationTimestamp,
    idxMessagesGroup,
    idxMessageRowsStreaming,
    idxMessagePartsRevisionOrdinal,
    idxProviderArtifactsRevisionKind,
    idxMessageAssetsAsset,
    idxGenerationRunsActiveTarget,
    idxGenerationRunsStateUpdated,
    idxAssistantMemoriesAssistant,
    idxMemoryEntriesVisible,
    idxMemoryEntriesRecent,
    idxMemoryEntriesDedupe,
    idxMessagePromptsConversationSnapshot,
    idxExtensionEntitiesKindOrder,
  ];
  late final Shape18 conversationRows = Shape18(
    source: i0.VersionedTable(
      entityName: 'conversation_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 messageRows = Shape19(
    source: i0.VersionedTable(
      entityName: 'message_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, message_order)',
        'UNIQUE(conversation_id, group_id, version)',
      ],
      columns: [
        _column_0,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_76,
        _column_77,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 conversationMcpServerRows = Shape2(
    source: i0.VersionedTable(
      entityName: 'conversation_mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(conversation_id, server_id)',
        'UNIQUE(conversation_id, ordinal)',
      ],
      columns: [_column_15, _column_33, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 chatStorageMetaRows = Shape3(
    source: i0.VersionedTable(
      entityName: 'chat_storage_meta_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 messagePartRows = Shape4(
    source: i0.VersionedTable(
      entityName: 'message_part_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(revision_id, ordinal)',
        'FOREIGN KEY(revision_id)REFERENCES message_rows(id)ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED',
        'CHECK(updated_at >= created_at)',
      ],
      columns: [
        _column_37,
        _column_38,
        _column_39,
        _column_34,
        _column_40,
        _column_41,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 providerArtifactRows = Shape5(
    source: i0.VersionedTable(
      entityName: 'provider_artifact_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(revision_id, kind)',
        'FOREIGN KEY(revision_id)REFERENCES message_rows(id)ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED',
        'CHECK(updated_at >= created_at)',
      ],
      columns: [
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 assetRows = Shape20(
    source: i0.VersionedTable(
      entityName: 'asset_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_2,
        _column_48,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 messageAssetRows = Shape7(
    source: i0.VersionedTable(
      entityName: 'message_asset_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(revision_id, asset_id, kind)'],
      columns: [_column_38, _column_49, _column_50, _column_40],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 assetGcRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'asset_gc_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(asset_id)'],
      columns: [_column_50, _column_51, _column_52, _column_53],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 gcAuditRows = Shape9(
    source: i0.VersionedTable(
      entityName: 'gc_audit_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_54, _column_55, _column_56, _column_57],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 assetReferenceDirtyRows = Shape10(
    source: i0.VersionedTable(
      entityName: 'asset_reference_dirty_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(revision_id)'],
      columns: [_column_49],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 generationRunRows = Shape11(
    source: i0.VersionedTable(
      entityName: 'generation_run_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'FOREIGN KEY(target_revision_id)REFERENCES message_rows(id)DEFERRABLE INITIALLY DEFERRED',
        'CHECK(updated_at >= created_at)',
        'CHECK(terminal_at IS NULL OR terminal_at >= created_at)',
        'CHECK((state IN (\'preparing\', \'requesting\', \'streaming\', \'waiting_tool\') AND terminal_at IS NULL)OR(state IN (\'completed\', \'failed\', \'cancelled\', \'interrupted\') AND terminal_at IS NOT NULL))',
        'CHECK(error_code IS NULL OR(length(error_code) BETWEEN 1 AND 128 AND state IN (\'failed\', \'cancelled\', \'interrupted\')))',
      ],
      columns: [
        _column_0,
        _column_15,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_2,
        _column_3,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 assistantRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'assistant_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 providerRows = Shape13(
    source: i0.VersionedTable(
      entityName: 'provider_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(provider_key)'],
      columns: [_column_65, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 providerGroupRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'provider_group_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 mcpServerRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 worldBookRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'world_book_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 assistantMemoryRows = Shape14(
    source: i0.VersionedTable(
      entityName: 'assistant_memory_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_66, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 quickPhraseRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'quick_phrase_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 searchServiceRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'search_service_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 ttsServiceRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'tts_service_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 instructionInjectionRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'instruction_injection_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 assistantTagRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'assistant_tag_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 preferenceRows = Shape15(
    source: i0.VersionedTable(
      entityName: 'preference_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_35, _column_36, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 memoryEntryRows = Shape16(
    source: i0.VersionedTable(
      entityName: 'memory_entry_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK((scope = \'global\' AND assistant_id IS NULL)OR(scope = \'assistant\' AND assistant_id IS NOT NULL))',
        'CHECK(entry_updated_at >= entry_created_at)',
      ],
      columns: [
        _column_0,
        _column_64,
        _column_67,
        _column_5,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_41,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 userProfileFieldRows = Shape12(
    source: i0.VersionedTable(
      entityName: 'user_profile_field_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_64, _column_41, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 messagePromptRows = Shape17(
    source: i0.VersionedTable(
      entityName: 'message_prompt_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(revision_id)',
        'FOREIGN KEY(revision_id)REFERENCES message_rows(id)ON DELETE CASCADE',
      ],
      columns: [_column_39, _column_38, _column_41, _column_74, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 tombstoneRows = Shape21(
    source: i0.VersionedTable(
      entityName: 'tombstone_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scope, entity_id)'],
      columns: [_column_78, _column_79, _column_80, _column_81],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape22 extensionEntityRows = Shape22(
    source: i0.VersionedTable(
      entityName: 'extension_entity_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kind, id)'],
      columns: [
        _column_40,
        _column_0,
        _column_64,
        _column_82,
        _column_41,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxConversationsUpdatedAt = i1.Index(
    'idx_conversations_updated_at',
    'CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at DESC, id ASC)',
  );
  final i1.Index idxConversationsAssistant = i1.Index(
    'idx_conversations_assistant',
    'CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id)',
  );
  final i1.Index idxMessagesConversationOrder = i1.Index(
    'idx_messages_conversation_order',
    'CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order, id)',
  );
  final i1.Index idxMessagesConversationTimestamp = i1.Index(
    'idx_messages_conversation_timestamp',
    'CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp, id)',
  );
  final i1.Index idxMessagesGroup = i1.Index(
    'idx_messages_group',
    'CREATE INDEX idx_messages_group ON message_rows (conversation_id, group_id, version, id)',
  );
  final i1.Index idxMessageRowsStreaming = i1.Index(
    'idx_message_rows_streaming',
    'CREATE INDEX idx_message_rows_streaming ON message_rows (id) WHERE is_streaming = 1',
  );
  final i1.Index idxMessagePartsRevisionOrdinal = i1.Index(
    'idx_message_parts_revision_ordinal',
    'CREATE INDEX idx_message_parts_revision_ordinal ON message_part_rows (conversation_id, revision_id, ordinal)',
  );
  final i1.Index idxProviderArtifactsRevisionKind = i1.Index(
    'idx_provider_artifacts_revision_kind',
    'CREATE INDEX idx_provider_artifacts_revision_kind ON provider_artifact_rows (conversation_id, revision_id, kind)',
  );
  final i1.Index idxMessageAssetsAsset = i1.Index(
    'idx_message_assets_asset',
    'CREATE INDEX idx_message_assets_asset ON message_asset_rows (asset_id, revision_id)',
  );
  final i1.Index idxGenerationRunsActiveTarget = i1.Index(
    'idx_generation_runs_active_target',
    'CREATE UNIQUE INDEX idx_generation_runs_active_target ON generation_run_rows (conversation_id, target_revision_id) WHERE state IN (\'preparing\', \'requesting\', \'streaming\', \'waiting_tool\')',
  );
  final i1.Index idxGenerationRunsStateUpdated = i1.Index(
    'idx_generation_runs_state_updated',
    'CREATE INDEX idx_generation_runs_state_updated ON generation_run_rows (state, updated_at, id)',
  );
  final i1.Index idxAssistantMemoriesAssistant = i1.Index(
    'idx_assistant_memories_assistant',
    'CREATE INDEX idx_assistant_memories_assistant ON assistant_memory_rows (assistant_id, id)',
  );
  final i1.Index idxMemoryEntriesVisible = i1.Index(
    'idx_memory_entries_visible',
    'CREATE INDEX idx_memory_entries_visible ON memory_entry_rows (status, type, scope, assistant_id)',
  );
  final i1.Index idxMemoryEntriesRecent = i1.Index(
    'idx_memory_entries_recent',
    'CREATE INDEX idx_memory_entries_recent ON memory_entry_rows (status, type, entry_updated_at, id)',
  );
  final i1.Index idxMemoryEntriesDedupe = i1.Index(
    'idx_memory_entries_dedupe',
    'CREATE INDEX idx_memory_entries_dedupe ON memory_entry_rows (scope, assistant_id, type, content_normalized)',
  );
  final i1.Index idxMessagePromptsConversationSnapshot = i1.Index(
    'idx_message_prompts_conversation_snapshot',
    'CREATE INDEX idx_message_prompts_conversation_snapshot ON message_prompt_rows (conversation_id, carries_memory_snapshot)',
  );
  final i1.Index idxExtensionEntitiesKindOrder = i1.Index(
    'idx_extension_entities_kind_order',
    'CREATE INDEX idx_extension_entities_kind_order ON extension_entity_rows (kind, sort_order)',
  );
}

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isPinned =>
      columnsByName['is_pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get assistantId =>
      columnsByName['assistant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get truncateIndex =>
      columnsByName['truncate_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get versionSelectionsJson =>
      columnsByName['version_selections_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSummarizedMessageCount =>
      columnsByName['last_summarized_message_count']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get chatSuggestionsJson =>
      columnsByName['chat_suggestions_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get injectedMemoryHash =>
      columnsByName['injected_memory_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastMemoryExtractedOrder =>
      columnsByName['last_memory_extracted_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get chatModelProvider =>
      columnsByName['chat_model_provider']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get chatModelId =>
      columnsByName['chat_model_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get extrasJson =>
      columnsByName['extras_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'extras_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timestamp =>
      columnsByName['timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get modelId =>
      columnsByName['model_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalTokens =>
      columnsByName['total_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isStreaming =>
      columnsByName['is_streaming']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reasoningStartAt =>
      columnsByName['reasoning_start_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reasoningFinishedAt =>
      columnsByName['reasoning_finished_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get translation =>
      columnsByName['translation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reasoningSegmentsJson =>
      columnsByName['reasoning_segments_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promptTokens =>
      columnsByName['prompt_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completionTokens =>
      columnsByName['completion_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cachedTokens =>
      columnsByName['cached_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get messageOrder =>
      columnsByName['message_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get senderId =>
      columnsByName['sender_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get extrasJson =>
      columnsByName['extras_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sender_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentHash =>
      columnsByName['content_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteSize =>
      columnsByName['byte_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get thumbnailPath =>
      columnsByName['thumbnail_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastReferencedAt =>
      columnsByName['last_referenced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get extrasJson =>
      columnsByName['extras_json']! as i1.GeneratedColumn<String>;
}

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scope',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (scope IS NOT \'\')',
    );
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (entity_id IS NOT \'\')',
    );
i1.GeneratedColumn<int> _column_80(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );

class Shape22 extends i0.VersionedTable {
  Shape22({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
